matrix:
  include:
    - os: linux
      language: android
      jdk: oraclejdk8
      dist: trusty
      sudo: required
      android:
        components:
          - platform-tools
          - tools
          - build-tools-25.0.0
          - android-25
          - android-21
          - sys-img-armeabi-v7a-android-23
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-google_play_services

before_install: . .travis/before-install.sh
install:
- .travis/install.sh
- android list targets

before_script: .travis/before-ci.sh
script: .travis/ci.sh
